---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-monolith
  labels:
    app: nodeapp-monolith
spec:
  #type: NodePort
  #clusterIP: None
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: nodeapp-monolith

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-monolith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp-monolith
  template:
    metadata:
      labels:
        app: nodeapp-monolith
    spec:
      containers:
      - name: nodeapp-monolith
        imagePullPolicy: Always
        image: dckreg:5000/monolith:1.1
        env:
        - name: redisHost
          value:  demo.redis
        - name: redisPort
          value:  "12000"
        - name: sessionTimeout
          value:  "260"
        ports:
        - containerPort: 3000
        command:
        - sh
        - -c
        - node seed/product.js  && npm start
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nodeapp
  namespace: default
spec:
  rules:
  - host: monolith.k8t.io
    http:
      paths:
      - backend:
          serviceName: nodeapp-monolith
          servicePort: 3000
